application:
  message: Configured by Local Server
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://goals-microservice-mysql.mysql.database.azure.com:3306/goals
    username: spring@goals-microservice-mysql
    password: iCUvJWC9HUWxzoCiJ8X3EQ
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
