application:
  name: goalservice
  message: Configured by Local Server
server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://goals-microservice-mysql.mysql.database.azure.com:3306/goals
    username: spring@goals-microservice-mysql
    password: iCUvJWC9HUWxzoCiJ8X3EQ
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  jms:
    servicebus:
      connection-string: Endpoint=sb://goalsservice.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WSJdd5dkKAAs2SKz6qpaD4WlLbr2ssOpx+ASbP9dDdA=
      pricing-tier: standard
